// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: danmu.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DanmuServiceClient is the client API for DanmuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DanmuServiceClient interface {
	Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendResp, error)
	GetDanmus(ctx context.Context, in *GetDanmusReq, opts ...grpc.CallOption) (*GetDanmusResp, error)
}

type danmuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDanmuServiceClient(cc grpc.ClientConnInterface) DanmuServiceClient {
	return &danmuServiceClient{cc}
}

func (c *danmuServiceClient) Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendResp, error) {
	out := new(SendResp)
	err := c.cc.Invoke(ctx, "/pb.DanmuService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *danmuServiceClient) GetDanmus(ctx context.Context, in *GetDanmusReq, opts ...grpc.CallOption) (*GetDanmusResp, error) {
	out := new(GetDanmusResp)
	err := c.cc.Invoke(ctx, "/pb.DanmuService/GetDanmus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DanmuServiceServer is the server API for DanmuService service.
// All implementations must embed UnimplementedDanmuServiceServer
// for forward compatibility
type DanmuServiceServer interface {
	Send(context.Context, *SendReq) (*SendResp, error)
	GetDanmus(context.Context, *GetDanmusReq) (*GetDanmusResp, error)
	mustEmbedUnimplementedDanmuServiceServer()
}

// UnimplementedDanmuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDanmuServiceServer struct {
}

func (UnimplementedDanmuServiceServer) Send(context.Context, *SendReq) (*SendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedDanmuServiceServer) GetDanmus(context.Context, *GetDanmusReq) (*GetDanmusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDanmus not implemented")
}
func (UnimplementedDanmuServiceServer) mustEmbedUnimplementedDanmuServiceServer() {}

// UnsafeDanmuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DanmuServiceServer will
// result in compilation errors.
type UnsafeDanmuServiceServer interface {
	mustEmbedUnimplementedDanmuServiceServer()
}

func RegisterDanmuServiceServer(s grpc.ServiceRegistrar, srv DanmuServiceServer) {
	s.RegisterService(&DanmuService_ServiceDesc, srv)
}

func _DanmuService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DanmuServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DanmuService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DanmuServiceServer).Send(ctx, req.(*SendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DanmuService_GetDanmus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDanmusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DanmuServiceServer).GetDanmus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DanmuService/GetDanmus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DanmuServiceServer).GetDanmus(ctx, req.(*GetDanmusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DanmuService_ServiceDesc is the grpc.ServiceDesc for DanmuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DanmuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DanmuService",
	HandlerType: (*DanmuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _DanmuService_Send_Handler,
		},
		{
			MethodName: "GetDanmus",
			Handler:    _DanmuService_GetDanmus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "danmu.proto",
}
