package e

const (
	USER_NOT_FOUND      = "USER_NOT_FOUND"
	USER_WRONG_PASSWORD = "USER_WRONG_PASSWORD"
	USER_HAS_EXISTED    = "USER_HAS_EXISTED"

	UNAUTHENTICATED = "UNAUTHENTICATED"

	INTERNAL = "INTERNAL"
)
